# Generated by Django 2.2.6 on 2019-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=30)),
                ('quantidade_funcionarios', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
            ],
        ),
    ]
