# Generated by Django 2.2.6 on 2019-11-04 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=30)),
                ('numero_cracha', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alimento', models.CharField(max_length=30)),
                ('quantidade_alimento', models.IntegerField()),
                ('valor_alimento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_refeicao', models.DateField()),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.Empresa')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Desperdicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_desperdicio_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_refeicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistemaApp.Refeicao')),
            ],
        ),
    ]
