# Generated by Django 2.2.6 on 2019-11-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0004_auto_20191105_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='nome_alimento',
        ),
    ]
